CREATE TABLE IF NOT EXISTS Books(		
	    Book_ID SERIAL PRIMARY KEY,		
		Title VARCHAR(100),		
		Author VARCHAR(100),		
		Genre VARCHAR(50),		
		Published_Year INT,		
		Price NUMERIC(10,2),		
		Stock INT		
					
);

CREATE TABLE IF NOT EXISTS Customers(
	Customer_ID SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	Email VARCHAR(100),
	Phone VARCHAR(15),
	City VARCHAR(50),
	Country VARCHAR(150)
);


CREATE TABLE IF NOT EXISTS Orders(
		Order_ID SERIAL PRIMARY KEY,
		Customer_ID INT REFERENCES Customers(Customer_ID),
		Book_ID INT REFERENCES Books(Book_ID),
		Order_Date DATE,
		Quantity INT,
		Total_Amount NUMERIC(10,2)
);

-- I import data directly by import/export option 

SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

-- 1). RETRIVE ALL BOOKS IN THE FICTION GENRE.
SELECT * FROM Books
WHERE Genre='Fiction';

-- 2).FIND BOOKS PUBLISHED AFTER THE YEAR 1950.
SELECT * FROM Books
WHERE Published_Year>1950;

-- 3).LIST THE CUSTOMERS FROM THE CANANDA.
SELECT * FROM Customers
WHERE Country='Canada';

-- 4). SHOW ORDERS PLACED IN NOVEMBER 2023
SELECT * FROM Orders
WHERE Order_Date BETWEEN '2023-11-01' AND '2023-11-30';

-- 5). RETRIVE THE TOTAL STOCKS OF THE BOOKS AVALIABLE 
SELECT SUM(Stock) AS TOTAL_STOCK 
FROM Books;

-- 6).FIND THE DETAILS OF THE MOST EXPENSIVE BOOKS
SELECT * FROM Books 
ORDER BY Price DESC 
LIMIT 1;

-- 7).SHOW ALL THE CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF BOOK 
SELECT * FROM Orders 
Where Quantity>1;

-- 8). RETRIEVE ALL ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20
SELECT * FROM Orders
WHERE Total_Amount>20;

-- 9).LIST ALL GENRE AVALIABLE IN THE BOOKS TABLE
SELECT DISTINCT(Genre)
FROM Books;

--10).FIND THE BOOK WITH THE LOWEST STOCK
SELECT * FROM Books
ORDER BY Stock
LIMIT 1;

--11).CALCULATE THE TOTAL REVENUE GENERATED FROM ALL THE ORDERS
SELECT SUM(Total_Amount) AS TOTAL_REVENUE
FROM Orders;

--ADVANCED QUESTION
--12).RETRIEVE THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE
SELECT b.Genre,SUM(o.Quantity)
FROM Books b
JOIN
Orders o
ON b.Book_ID= o.Book_ID
GROUP BY b.Genre;

--13).FIND THE AVERAGE PRICE OF THE BOOKS IN THE FANTASY GENRE
SELECT AVG(Price) 
FROM Books
Where Genre='Fantasy';

--14).LIST CUSTOMERS WHO HAVE PLACED ATLEAST 2 ORDERS
-- 1 TYPE
SELECT c.Name,c.Email,c.Phone,c.City,c.Country
FROM Orders o
JOIN
Customers c
ON o.Customer_ID= c.Customer_ID
WHERE  Quantity>2;

-- 2 TYPE (MORE ACCURATE)
SELECT Customer_ID,COUNT(Order_ID)
FROM Orders 
GROUP BY  Customer_id
HAVING COUNT(Order_ID)>=2;


--15).FIND THE MOST FREQUENTLY ORDERED BOOK
SELECT Book_ID,COUNT(Order_ID) AS ORDER_COUNT
FROM Orders
GROUP BY Book_ID
ORDER BY ORDER_COUNT DESC 
LIMIT 1;

--16).SHOW THE TOP 3 MOST EXPENSIVE BOOK OF FANTASY GENRE
SELECT * 
FROM Books
WHERE Genre='Fantasy'
ORDER BY Price DESC
LIMIT 3;

--17).TOTAL QUANTITY OF BOOK SOLD BY EACH AUTHOR 
SELECT DISTINCT(b.Author),SUM(o.Quantity)
FROM Orders o
JOIN
Books b
ON o.Book_ID=b.Book_id
GROUP BY b.Author;

--18).LIST THE CITIES WHERE CUSTOMERS WHO SPENT MORE THAN $100  ARE LOCATED
SELECT DISTINCT c.City,(o.Total_Amount)
FROM Customers c
JOIN
Orders o
ON c.Customer_ID= o.Customer_ID
WHERE o.Total_Amount>100;

--19).FIND THE CUSTOMERS WHO SPENT MORE ON THE ORDERS
-- 1 TYPE
SELECT Customer_ID,Total_Amount
FROM Orders
ORDER BY Total_Amount DESC
LIMIT 1;

-- 2 TYPE(MORE ACCURATE )
SELECT c.Name, SUM(o.Total_Amount) AS Total_Spent
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Name
ORDER BY Total_Spent DESC
LIMIT 1;

--20).CALCULATE THE STOCKS REMAINING AFTER FULFILLING ALL ORDERS
SELECT b.Book_ID,b.Title,b.Stock,COALESCE(SUM(o.Quantity),0) AS ORDER_COUNT,
b.Stock-COALESCE(SUM(o.Quantity),0) AS REMIANING
FROM Books b
LEFT JOIN
Orders o
ON b.book_ID=o.Book_ID
GROUP BY b.Book_ID;

